# Site settings
title: David Petzel
email: dave@petzel.email
description: > # this means to ignore newlines until "baseurl:"
  I do random stuff and sometimes I write about it
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dpetzel.info" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  dpetzel
linkedin_pub_profile: https://www.linkedin.com/pub/david-petzel/3/2bb/4bb

# Build settings
markdown: kramdown


################################################################################
# Items below this line have nothing to do with Jekyll and are just
# used by the Rake tasks to make life easier
################################################################################
post:
  template: _post.md.template
  extension: md
page:
  template: _page.md.template
  extension: md
editor: /opt/sublime_text/sublime_text
git:
  branch: master
